# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: closeloop_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import closeloop_params_pb2 as closeloop__params__pb2
import closeloop_metric_pb2 as closeloop__metric__pb2
import closeloop_hdmap_pb2 as closeloop__hdmap__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='closeloop_service.proto',
  package='adu.workers.closeloop',
  syntax='proto2',
  serialized_pb=_b('\n\x17\x63loseloop_service.proto\x12\x15\x61\x64u.workers.closeloop\x1a\x16\x63loseloop_params.proto\x1a\x16\x63loseloop_metric.proto\x1a\x15\x63loseloop_hdmap.proto2\xb5\x01\n\rMetricService\x12P\n\x0bStartMetric\x12\x1d.adu.workers.closeloop.Metric\x1a .adu.workers.closeloop.MetricACK\"\x00\x12R\n\nStopMetric\x12\x1d.adu.workers.closeloop.Metric\x1a#.adu.workers.closeloop.MetricResult\"\x00\x32\x62\n\x0cHDMapService\x12R\n\x0cGetHDmapInfo\x12\x1c.adu.workers.closeloop.Point\x1a\".adu.workers.closeloop.HDMapParams\"\x00')
  ,
  dependencies=[closeloop__params__pb2.DESCRIPTOR,closeloop__metric__pb2.DESCRIPTOR,closeloop__hdmap__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
