# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calibrator_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='calibrator_message.proto',
  package='adu.workers.calibrator',
  syntax='proto2',
  serialized_pb=_b('\n\x18\x63\x61librator_message.proto\x12\x16\x61\x64u.workers.calibrator\"K\n\x1b\x43\x61meraLidarCalibrateRequest\x12,\n\x03\x63md\x18\x01 \x02(\x0e\x32\x1f.adu.workers.calibrator.CmdType\"a\n\x1c\x43\x61meraLidarCalibrateResponse\x12/\n\x04\x63ode\x18\x01 \x02(\x0e\x32!.adu.workers.calibrator.ErrorCode\x12\x10\n\x08progress\x18\x02 \x01(\x01*f\n\tErrorCode\x12\x06\n\x02OK\x10\x00\x12\x19\n\x15\x45RROR_INVALID_REQUEST\x10\x01\x12\x1c\n\x18\x45RROR_PARAMETERS_INVALID\x10\x65\x12\x18\n\x14\x45RROR_CALIBRATE_FAIL\x10\x66*)\n\x07\x43mdType\x12\t\n\x05START\x10\x01\x12\t\n\x05\x43HECK\x10\x02\x12\x08\n\x04STOP\x10\x03*j\n\nCameraType\x12\x0e\n\nSMARTEREYE\x10\x01\x12\x10\n\x0cLEFT_FORWARD\x10\x02\x12\r\n\tLEFT_BACK\x10\x03\x12\x11\n\rRIGHT_FORWARD\x10\x04\x12\x0e\n\nRIGHT_BACK\x10\x05\x12\x08\n\x04REAR\x10\x06*6\n\tLidarType\x12\x08\n\x04LEFT\x10\x01\x12\t\n\x05RIGHT\x10\x02\x12\x08\n\x04\x42\x41\x43K\x10\x03\x12\n\n\x06\x46USION\x10\x04\x42\x02P\x01')
)

_ERRORCODE = _descriptor.EnumDescriptor(
  name='ErrorCode',
  full_name='adu.workers.calibrator.ErrorCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_INVALID_REQUEST', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_PARAMETERS_INVALID', index=2, number=101,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_CALIBRATE_FAIL', index=3, number=102,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=228,
  serialized_end=330,
)
_sym_db.RegisterEnumDescriptor(_ERRORCODE)

ErrorCode = enum_type_wrapper.EnumTypeWrapper(_ERRORCODE)
_CMDTYPE = _descriptor.EnumDescriptor(
  name='CmdType',
  full_name='adu.workers.calibrator.CmdType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='START', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHECK', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STOP', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=332,
  serialized_end=373,
)
_sym_db.RegisterEnumDescriptor(_CMDTYPE)

CmdType = enum_type_wrapper.EnumTypeWrapper(_CMDTYPE)
_CAMERATYPE = _descriptor.EnumDescriptor(
  name='CameraType',
  full_name='adu.workers.calibrator.CameraType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SMARTEREYE', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEFT_FORWARD', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEFT_BACK', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RIGHT_FORWARD', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RIGHT_BACK', index=4, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REAR', index=5, number=6,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=375,
  serialized_end=481,
)
_sym_db.RegisterEnumDescriptor(_CAMERATYPE)

CameraType = enum_type_wrapper.EnumTypeWrapper(_CAMERATYPE)
_LIDARTYPE = _descriptor.EnumDescriptor(
  name='LidarType',
  full_name='adu.workers.calibrator.LidarType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LEFT', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RIGHT', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='BACK', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FUSION', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=483,
  serialized_end=537,
)
_sym_db.RegisterEnumDescriptor(_LIDARTYPE)

LidarType = enum_type_wrapper.EnumTypeWrapper(_LIDARTYPE)
OK = 0
ERROR_INVALID_REQUEST = 1
ERROR_PARAMETERS_INVALID = 101
ERROR_CALIBRATE_FAIL = 102
START = 1
CHECK = 2
STOP = 3
SMARTEREYE = 1
LEFT_FORWARD = 2
LEFT_BACK = 3
RIGHT_FORWARD = 4
RIGHT_BACK = 5
REAR = 6
LEFT = 1
RIGHT = 2
BACK = 3
FUSION = 4



_CAMERALIDARCALIBRATEREQUEST = _descriptor.Descriptor(
  name='CameraLidarCalibrateRequest',
  full_name='adu.workers.calibrator.CameraLidarCalibrateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmd', full_name='adu.workers.calibrator.CameraLidarCalibrateRequest.cmd', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=127,
)


_CAMERALIDARCALIBRATERESPONSE = _descriptor.Descriptor(
  name='CameraLidarCalibrateResponse',
  full_name='adu.workers.calibrator.CameraLidarCalibrateResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='adu.workers.calibrator.CameraLidarCalibrateResponse.code', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='progress', full_name='adu.workers.calibrator.CameraLidarCalibrateResponse.progress', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=226,
)

_CAMERALIDARCALIBRATEREQUEST.fields_by_name['cmd'].enum_type = _CMDTYPE
_CAMERALIDARCALIBRATERESPONSE.fields_by_name['code'].enum_type = _ERRORCODE
DESCRIPTOR.message_types_by_name['CameraLidarCalibrateRequest'] = _CAMERALIDARCALIBRATEREQUEST
DESCRIPTOR.message_types_by_name['CameraLidarCalibrateResponse'] = _CAMERALIDARCALIBRATERESPONSE
DESCRIPTOR.enum_types_by_name['ErrorCode'] = _ERRORCODE
DESCRIPTOR.enum_types_by_name['CmdType'] = _CMDTYPE
DESCRIPTOR.enum_types_by_name['CameraType'] = _CAMERATYPE
DESCRIPTOR.enum_types_by_name['LidarType'] = _LIDARTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CameraLidarCalibrateRequest = _reflection.GeneratedProtocolMessageType('CameraLidarCalibrateRequest', (_message.Message,), dict(
  DESCRIPTOR = _CAMERALIDARCALIBRATEREQUEST,
  __module__ = 'calibrator_message_pb2'
  # @@protoc_insertion_point(class_scope:adu.workers.calibrator.CameraLidarCalibrateRequest)
  ))
_sym_db.RegisterMessage(CameraLidarCalibrateRequest)

CameraLidarCalibrateResponse = _reflection.GeneratedProtocolMessageType('CameraLidarCalibrateResponse', (_message.Message,), dict(
  DESCRIPTOR = _CAMERALIDARCALIBRATERESPONSE,
  __module__ = 'calibrator_message_pb2'
  # @@protoc_insertion_point(class_scope:adu.workers.calibrator.CameraLidarCalibrateResponse)
  ))
_sym_db.RegisterMessage(CameraLidarCalibrateResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('P\001'))
# @@protoc_insertion_point(module_scope)
