# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openapi_client_fm_grpc.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='openapi_client_fm_grpc.proto',
  package='adu.workers.openapi',
  syntax='proto2',
  serialized_pb=_b('\n\x1copenapi_client_fm_grpc.proto\x12\x13\x61\x64u.workers.openapi\"X\n\x11\x43ontrollerRequest\x12\x36\n\x0crequest_type\x18\x01 \x02(\x0e\x32 .adu.workers.openapi.RequestType\x12\x0b\n\x03vin\x18\x02 \x01(\t\"\xbf\x01\n\x0f\x43ontrollerReply\x12\x32\n\nreply_type\x18\x01 \x02(\x0e\x32\x1e.adu.workers.openapi.ReplyType\x12;\n\x0fvehicle_run_cmd\x18\x02 \x01(\x0e\x32\".adu.workers.openapi.VehicleRunCmd\x12;\n\x0f\x64\x65vice_cont_cmd\x18\x03 \x01(\x0e\x32\".adu.workers.openapi.DeviceContCmd*=\n\rVehicleRunCmd\x12\x11\n\rSTOP_STRAIGHT\x10\x00\x12\x0e\n\nSTOP_ASIDE\x10\x01\x12\t\n\x05GO_ON\x10\x02*.\n\rDeviceContCmd\x12\x0e\n\nCLOSE_DOOR\x10\x00\x12\r\n\tOPEN_DOOR\x10\x01*\x16\n\x0bRequestType\x12\x07\n\x03VIN\x10\x00*8\n\tReplyType\x12\x13\n\x0fVEHICLE_RUN_CMD\x10\x00\x12\x16\n\x12\x44\x45VICE_CONTROL_CMD\x10\x01\x32r\n\x0eOpenApiService\x12`\n\nController\x12&.adu.workers.openapi.ControllerRequest\x1a$.adu.workers.openapi.ControllerReply\"\x00(\x01\x30\x01')
)

_VEHICLERUNCMD = _descriptor.EnumDescriptor(
  name='VehicleRunCmd',
  full_name='adu.workers.openapi.VehicleRunCmd',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STOP_STRAIGHT', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='STOP_ASIDE', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GO_ON', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=337,
  serialized_end=398,
)
_sym_db.RegisterEnumDescriptor(_VEHICLERUNCMD)

VehicleRunCmd = enum_type_wrapper.EnumTypeWrapper(_VEHICLERUNCMD)
_DEVICECONTCMD = _descriptor.EnumDescriptor(
  name='DeviceContCmd',
  full_name='adu.workers.openapi.DeviceContCmd',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='CLOSE_DOOR', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='OPEN_DOOR', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=400,
  serialized_end=446,
)
_sym_db.RegisterEnumDescriptor(_DEVICECONTCMD)

DeviceContCmd = enum_type_wrapper.EnumTypeWrapper(_DEVICECONTCMD)
_REQUESTTYPE = _descriptor.EnumDescriptor(
  name='RequestType',
  full_name='adu.workers.openapi.RequestType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='VIN', index=0, number=0,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=448,
  serialized_end=470,
)
_sym_db.RegisterEnumDescriptor(_REQUESTTYPE)

RequestType = enum_type_wrapper.EnumTypeWrapper(_REQUESTTYPE)
_REPLYTYPE = _descriptor.EnumDescriptor(
  name='ReplyType',
  full_name='adu.workers.openapi.ReplyType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='VEHICLE_RUN_CMD', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DEVICE_CONTROL_CMD', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=472,
  serialized_end=528,
)
_sym_db.RegisterEnumDescriptor(_REPLYTYPE)

ReplyType = enum_type_wrapper.EnumTypeWrapper(_REPLYTYPE)
STOP_STRAIGHT = 0
STOP_ASIDE = 1
GO_ON = 2
CLOSE_DOOR = 0
OPEN_DOOR = 1
VIN = 0
VEHICLE_RUN_CMD = 0
DEVICE_CONTROL_CMD = 1



_CONTROLLERREQUEST = _descriptor.Descriptor(
  name='ControllerRequest',
  full_name='adu.workers.openapi.ControllerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_type', full_name='adu.workers.openapi.ControllerRequest.request_type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vin', full_name='adu.workers.openapi.ControllerRequest.vin', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=53,
  serialized_end=141,
)


_CONTROLLERREPLY = _descriptor.Descriptor(
  name='ControllerReply',
  full_name='adu.workers.openapi.ControllerReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reply_type', full_name='adu.workers.openapi.ControllerReply.reply_type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='vehicle_run_cmd', full_name='adu.workers.openapi.ControllerReply.vehicle_run_cmd', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='device_cont_cmd', full_name='adu.workers.openapi.ControllerReply.device_cont_cmd', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=144,
  serialized_end=335,
)

_CONTROLLERREQUEST.fields_by_name['request_type'].enum_type = _REQUESTTYPE
_CONTROLLERREPLY.fields_by_name['reply_type'].enum_type = _REPLYTYPE
_CONTROLLERREPLY.fields_by_name['vehicle_run_cmd'].enum_type = _VEHICLERUNCMD
_CONTROLLERREPLY.fields_by_name['device_cont_cmd'].enum_type = _DEVICECONTCMD
DESCRIPTOR.message_types_by_name['ControllerRequest'] = _CONTROLLERREQUEST
DESCRIPTOR.message_types_by_name['ControllerReply'] = _CONTROLLERREPLY
DESCRIPTOR.enum_types_by_name['VehicleRunCmd'] = _VEHICLERUNCMD
DESCRIPTOR.enum_types_by_name['DeviceContCmd'] = _DEVICECONTCMD
DESCRIPTOR.enum_types_by_name['RequestType'] = _REQUESTTYPE
DESCRIPTOR.enum_types_by_name['ReplyType'] = _REPLYTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ControllerRequest = _reflection.GeneratedProtocolMessageType('ControllerRequest', (_message.Message,), dict(
  DESCRIPTOR = _CONTROLLERREQUEST,
  __module__ = 'openapi_client_fm_grpc_pb2'
  # @@protoc_insertion_point(class_scope:adu.workers.openapi.ControllerRequest)
  ))
_sym_db.RegisterMessage(ControllerRequest)

ControllerReply = _reflection.GeneratedProtocolMessageType('ControllerReply', (_message.Message,), dict(
  DESCRIPTOR = _CONTROLLERREPLY,
  __module__ = 'openapi_client_fm_grpc_pb2'
  # @@protoc_insertion_point(class_scope:adu.workers.openapi.ControllerReply)
  ))
_sym_db.RegisterMessage(ControllerReply)


# @@protoc_insertion_point(module_scope)
