# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: collection_error_code.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='collection_error_code.proto',
  package='adu.workers.collection',
  syntax='proto2',
  serialized_pb=_b('\n\x1b\x63ollection_error_code.proto\x12\x16\x61\x64u.workers.collection*\xe2\x03\n\tErrorCode\x12\x0b\n\x07SUCCESS\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x12\x11\n\rERROR_REQUEST\x10\x03\x12\x1d\n\x19\x45RROR_SERVICE_NO_RESPONSE\x10\x04\x12\x1a\n\x16\x45RROR_DISKINFO_SERVICE\x10\x65\x12\x18\n\x14\x45RROR_DISKINFO_ERROR\x10\x66\x12\x16\n\x12\x45RROR_DISK_UNMOUNT\x10g\x12\x19\n\x15\x45RROR_CARSTATUS_EMPTY\x10h\x12\x14\n\x10\x45RROR_SPEED_LACK\x10i\x12\x17\n\x13\x45RROR_ODOMETER_LACK\x10j\x12\x19\n\x15\x45RROR_RTKSTATUS_EMPTY\x10k\x12\x1e\n\x19\x45RROR_MAPGRPC_NOT_CONNECT\x10\xc9\x01\x12!\n\x1c\x45RROR_DYNAMIC_ALIGN_RESPONSE\x10\xca\x01\x12\x1f\n\x1a\x45RROR_EIGHT_ROUTE_RESPONSE\x10\xcb\x01\x12\x1f\n\x1a\x45RROR_DATA_VERIFY_RESPONSE\x10\xcc\x01\x12!\n\x1c\x45RROR_DATA_VERIFY_TASK_EMPTY\x10\xcd\x01\x12\x17\n\x12SUCCESS_TASK_EMPTY\x10\xad\x02\x12\x17\n\x12SUCCESS_TASK_STOCK\x10\xae\x02')
)

_ERRORCODE = _descriptor.EnumDescriptor(
  name='ErrorCode',
  full_name='adu.workers.collection.ErrorCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=1, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_REQUEST', index=2, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_SERVICE_NO_RESPONSE', index=3, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_DISKINFO_SERVICE', index=4, number=101,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_DISKINFO_ERROR', index=5, number=102,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_DISK_UNMOUNT', index=6, number=103,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_CARSTATUS_EMPTY', index=7, number=104,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_SPEED_LACK', index=8, number=105,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_ODOMETER_LACK', index=9, number=106,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_RTKSTATUS_EMPTY', index=10, number=107,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_MAPGRPC_NOT_CONNECT', index=11, number=201,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_DYNAMIC_ALIGN_RESPONSE', index=12, number=202,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_EIGHT_ROUTE_RESPONSE', index=13, number=203,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_DATA_VERIFY_RESPONSE', index=14, number=204,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR_DATA_VERIFY_TASK_EMPTY', index=15, number=205,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS_TASK_EMPTY', index=16, number=301,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='SUCCESS_TASK_STOCK', index=17, number=302,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=56,
  serialized_end=538,
)
_sym_db.RegisterEnumDescriptor(_ERRORCODE)

ErrorCode = enum_type_wrapper.EnumTypeWrapper(_ERRORCODE)
SUCCESS = 1
ERROR = 2
ERROR_REQUEST = 3
ERROR_SERVICE_NO_RESPONSE = 4
ERROR_DISKINFO_SERVICE = 101
ERROR_DISKINFO_ERROR = 102
ERROR_DISK_UNMOUNT = 103
ERROR_CARSTATUS_EMPTY = 104
ERROR_SPEED_LACK = 105
ERROR_ODOMETER_LACK = 106
ERROR_RTKSTATUS_EMPTY = 107
ERROR_MAPGRPC_NOT_CONNECT = 201
ERROR_DYNAMIC_ALIGN_RESPONSE = 202
ERROR_EIGHT_ROUTE_RESPONSE = 203
ERROR_DATA_VERIFY_RESPONSE = 204
ERROR_DATA_VERIFY_TASK_EMPTY = 205
SUCCESS_TASK_EMPTY = 301
SUCCESS_TASK_STOCK = 302


DESCRIPTOR.enum_types_by_name['ErrorCode'] = _ERRORCODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
